name: Staging Plan
on:
  push:
    branches: ['*']
  pull_request:

permissions:
  contents: read
  pull-requests: write

jobs:
  staging-main:
    uses: ./.github/workflows/shared.yml
    with:
      environment: staging
      working_directory: ./env/staging
      auto_apply: false
    secrets: inherit
  
  staging-test-bucket:
    uses: ./.github/workflows/shared.yml
    with:
      environment: staging
      working_directory: ./env/staging/test-bucket
      auto_apply: false
    secrets: inherit

