name: Staging

on:
  pull_request:
    branches: [main]

jobs:
  deploy-staging:
    uses: ./.github/workflows/shared.yml
    with:
      environment: staging
      working_directory: ./environments/staging
      auto_apply: ${{ github.ref == 'refs/heads/staging' && github.event_name == 'push' }}
    secrets: inherit
